language: java
jdk: openjdk11
after_success:
- ./upload.sh
- ./publish-javadoc.sh
before_install:
- '[ "$TRAVIS_PULL_REQUEST" == "false" ] && openssl aes-256-cbc -K $encrypted_81a36e1dcef5_key -iv $encrypted_81a36e1dcef5_iv -in secring.gpg.enc -out secring.gpg -d || echo "no decryption for pull requests"'
